# Generated by Django 4.1.3 on 2022-11-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0008_remove_post_title_tag_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(choices=[('СТ', 'Статья'), ('НО', 'Новость')], default='НО', max_length=2),
        ),
    ]
