# Generated by Django 4.1.3 on 2022-11-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0009_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='news', max_length=2),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
