# Generated by Django 4.1.3 on 2022-11-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0013_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user_rate',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='blog_posts', to='newspaper.author'),
        ),
    ]
