"""
Django settings for news project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from pathlib import Path
import logging
import datetime as dt
#import loggers as loggers
import os
import pytz


#today = dt.datetime.today()

# logging.basicConfig(level=logging.DEBUG)

# logging.log(logging.DEBUG, "This is our Debug message " f"{today.day:02d}-{today.month:02d}-{today.year}")
# logging.log(logging.INFO, "This is our Info message " f"{today.day:02d}-{today.month:02d}-{today.year}")
# logging.log(logging.WARNING, "This is our Warning message " f"{today.day:02d}-{today.month:02d}-{today.year}")
# logging.log(logging.ERROR, "This is our Error message " f"{today.day:02d}-{today.month:02d}-{today.year}")
# logging.log(logging.CRITICAL, "This is our Critical message " f"{today.day:02d}-{today.month:02d}-{today.year}")

# LOGGING ={
#     'version': 1,
#     'disable_existing_loggers': False,
#     'filters': {
#         'require_debug_false': {
#             '()': 'django.utils.log.RequireDebugFalse',
#         },
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',
#         },
#     },
#     'formatters': {
#         'django.server12': {
#             '()': 'django.utils.log.ServerFormatter',
#             'format': '%(server_time)s %(message)s %(pathname)s %(asctime)s %(levelname)s' #'{exc_info}' '{module}'
#         }
#     },
#
#     'handlers': {
#         'console': {
#             'level': 'DEBUG',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#         },
#         'django.server': {
#             'level': 'INFO',
#             'filters': ['require_debug_false'],
#             'class': 'logging.StreamHandler',
#             'formatter': 'django.server12',
#             'filename': 'general.log'
#
#         },
#         'django.server1': {
#             'level': 'INFO',
#             'filters': ['require_debug_false'],
#             'class': 'logging.StreamHandler',
#             'formatter': 'django12.server',
#             'filename': 'general.log'
#
#         },
#         'mail_admins': {
#             'level': 'ERROR',
#             'filters': ['require_debug_false'],
#             'class': 'django.utils.log.AdminEmailHandler', #'logging.FileHandler'
#             'filename': 'errors.log'
#
#         },
#         'mail_admins1': {
#             'level': 'ERROR',
#             'filters': ['require_debug_false'],
#             'class': 'logging.FileHandler',
#             'filename': 'errors.log'
#
#         }
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console', 'general.log'],
#             'level': 'DEBUG',
#         },
#         'django.server': {
#             'handlers': ['errors.log', 'mail_admins'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#
#         'django.request ': {
#             'handlers': ['errors.log', 'mail_admins'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#         'django.template': {
#             'handlers': ['errors.log'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#         'django.db.backends': {
#             'handlers': ['errors.log'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#         'django.security': {
#             'handlers': ['security.log'],
#             'level': 'INFO',
#             'propagate': False,
#         },
#     }
# }



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=6%8s+6@7q=9#r-6r4a*3hvwx=d(ld=b$a1u_cf&=&%iq(yrfc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',

    'django.contrib.messages',
    'django.contrib.staticfiles',
    'newspaper',
    'members',
    'django_filters',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'django.contrib.sites',
    #'basic',
    ]

SITE_ID = 1
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
            'SCOPE': [
                'profile',
                'email'
            ],
            'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.locale.LocaleMiddleware',

    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #'basic.middlewares.TimezoneMiddleware',
]

ROOT_URLCONF = 'news.urls'


LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    ]


WSGI_APPLICATION = 'news.wsgi.application'

LANGUAGES = [
    ('en', 'English'),
    ('ru', 'Русский')
]


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = 'smtp.yandex.ru'  # адрес сервера Яндекс-почты для всех один и тот же
EMAIL_PORT = 465  # порт smtp сервера тоже одинаковый
EMAIL_HOST_USER = ''  # ваше имя пользователя, например, если ваша почта user@yandex.ru,
# то сюда надо писать user, иными словами, это всё то что идёт до собаки
EMAIL_HOST_PASSWORD = ''  # пароль от почты
EMAIL_USE_SSL = True  # Яндекс использует ssl, подробнее о том, что это, почитайте в
# дополнительных источниках, но включать его здесь обязательно

